<?php

namespace BAJAMA\Traffic;

use PDO;
use Throwable;

/**
 * BAJAMA Central Traffic Lookup Engine V1
 *
 * Tujuan:
 * - membaca evidence dari traffic_observations
 * - mengidentifikasi provider/application/service
 * - memisahkan technical classification dari business category
 * - menghitung confidence
 * - menghasilkan knowledge object untuk traffic_lookup
 *
 * V1 BELUM menulis ke traffic_catalog.
 * V1 BELUM dipanggil oleh worker.
 *
 * Compatible dengan PHP 7.4+
 */
class TrafficCentralLookupService
{
    private PDO $db;

    public function __construct(PDO $db)
    {
        $this->db = $db;
    }

    /**
     * Lookup satu hostname berdasarkan evidence database.
     */
    public function lookupHostname(string $hostname): array
    {
        $hostname = $this->normalizeHostname($hostname);

        if ($hostname === null) {
            return [
                'success' => false,
                'hostname' => null,
                'error' => 'Hostname tidak valid.',
            ];
        }

        $evidence = $this->collectEvidence($hostname);
        $intelligence = $this->classifyHostname($hostname, $evidence);

        return [
            'success' => true,
            'hostname' => $hostname,
            'provider' => $intelligence['provider'],
            'application' => $intelligence['application'],
            'service' => $intelligence['service'],
            'technical_classification' => $intelligence['technical_classification'],
            'business_category' => $intelligence['business_category'],
            'confidence' => $intelligence['confidence'],
            'normalized_domain' => $intelligence['normalized_domain'],
            'evidence' => $evidence,
        ];
    }

    /**
     * Simpan hasil Central Lookup ke knowledge table.
     *
     * Method ini idempotent berdasarkan hostname_pattern.
     */
    public function persistResult(array $result): array
    {
        if (empty($result['success']) || empty($result['hostname'])) {
            throw new \InvalidArgumentException(
                'Hasil Central Lookup tidak valid.'
            );
        }

        $hostname = $this->normalizeHostname(
            (string)$result['hostname']
        );

        if ($hostname === null) {
            throw new \InvalidArgumentException(
                'Hostname hasil lookup tidak valid.'
            );
        }

        $categorySlug = strtolower(
            trim((string)($result['business_category'] ?? 'browser'))
        );

        if ($categorySlug === '') {
            $categorySlug = 'browser';
        }

        $categoryName = ucwords(
            str_replace(
                ['-', '_'],
                ' ',
                $categorySlug
            )
        );

        $categoryDescription =
            'Business category generated by BAJAMA Central Lookup.';

        /*
         * Central Lookup hanya membuat kategori baru jika
         * klasifikasi memang mempunyai identitas.
         *
         * Unknown tetap Browser / General.
         */
        $categoryId = $this->ensureLookupCategory(
            $categorySlug,
            $categoryName,
            $categoryDescription
        );

        $evidenceJson = json_encode(
            $result['evidence'] ?? [],
            JSON_UNESCAPED_SLASHES |
            JSON_UNESCAPED_UNICODE |
            JSON_PRETTY_PRINT
        );

        if ($evidenceJson === false) {
            $evidenceJson = '{}';
        }

        $sql = "
            INSERT INTO traffic_lookup (
                hostname_pattern,
                normalized_domain,
                provider,
                application,
                service,
                technical_classification,
                category_id,
                confidence,
                evidence,
                source_type,
                enabled,
                first_seen_at,
                last_seen_at
            )
            VALUES (
                :hostname_pattern,
                :normalized_domain,
                :provider,
                :application,
                :service,
                :technical_classification,
                :category_id,
                :confidence,
                :evidence,
                'CENTRAL_LOOKUP',
                1,
                COALESCE(
                    JSON_UNQUOTE(
                        JSON_EXTRACT(:evidence_first, '$.first_seen_at')
                    ),
                    NULL
                ),
                COALESCE(
                    JSON_UNQUOTE(
                        JSON_EXTRACT(:evidence_last, '$.last_seen_at')
                    ),
                    NULL
                )
            )
            ON DUPLICATE KEY UPDATE
                normalized_domain = VALUES(normalized_domain),
                provider = VALUES(provider),
                application = VALUES(application),
                service = VALUES(service),
                technical_classification =
                    VALUES(technical_classification),
                category_id = VALUES(category_id),
                confidence = VALUES(confidence),
                evidence = VALUES(evidence),
                enabled = 1,
                last_seen_at = VALUES(last_seen_at),
                updated_at = CURRENT_TIMESTAMP
        ";

        /*
         * Ambil first/last seen langsung dari evidence.
         */
        $evidence = $result['evidence'] ?? [];

        $firstSeen = $evidence['first_seen_at'] ?? null;
        $lastSeen = $evidence['last_seen_at'] ?? null;

        $stmt = $this->db->prepare($sql);

        $stmt->execute([
            ':hostname_pattern' =>
                $hostname,

            ':normalized_domain' =>
                (string)($result['normalized_domain'] ?? $hostname),

            ':provider' =>
                $result['provider'] ?? null,

            ':application' =>
                $result['application'] ?? null,

            ':service' =>
                $result['service'] ?? null,

            ':technical_classification' =>
                $result['technical_classification'] ?? null,

            ':category_id' =>
                $categoryId,

            ':confidence' =>
                (float)($result['confidence'] ?? 0),

            ':evidence' =>
                $evidenceJson,

            ':evidence_first' =>
                json_encode(
                    ['first_seen_at' => $firstSeen],
                    JSON_UNESCAPED_SLASHES
                ),

            ':evidence_last' =>
                json_encode(
                    ['last_seen_at' => $lastSeen],
                    JSON_UNESCAPED_SLASHES
                ),
        ]);

        $lookupStmt = $this->db->prepare("
            SELECT id
            FROM traffic_lookup
            WHERE hostname_pattern = :hostname
            LIMIT 1
        ");

        $lookupStmt->execute([
            ':hostname' => $hostname,
        ]);

        return [
            'id' => (int)$lookupStmt->fetchColumn(),
            'hostname' => $hostname,
            'category_id' => $categoryId,
            'category_slug' => $categorySlug,
        ];
    }

    /**
     * Pastikan kategori Central Lookup tersedia.
     */
    private function ensureLookupCategory(
        string $slug,
        string $name,
        string $description
    ): int {
        $slug = strtolower(trim($slug));

        $stmt = $this->db->prepare("
            SELECT id
            FROM traffic_categories
            WHERE slug = :slug
            LIMIT 1
        ");

        $stmt->execute([
            ':slug' => $slug,
        ]);

        $existing = $stmt->fetchColumn();

        if ($existing !== false) {
            return (int)$existing;
        }

        $sortStmt = $this->db->query("
            SELECT COALESCE(MAX(sort_order), 0)
            FROM traffic_categories
        ");

        $sortOrder = ((int)$sortStmt->fetchColumn()) + 10;

        $insert = $this->db->prepare("
            INSERT INTO traffic_categories (
                name,
                slug,
                description,
                icon,
                enabled,
                sort_order
            )
            VALUES (
                :name,
                :slug,
                :description,
                'bi-diagram-3',
                1,
                :sort_order
            )
        ");

        $insert->execute([
            ':name' => $name,
            ':slug' => $slug,
            ':description' => $description,
            ':sort_order' => $sortOrder,
        ]);

        return (int)$this->db->lastInsertId();
    }

    /**
     * Ambil hostname unik dari traffic observations.
     */
    public function listObservedHostnames(int $limit = 1000): array
    {
        $limit = max(1, min(10000, $limit));

        $sql = "
            SELECT
                LOWER(TRIM(hostname)) AS hostname,
                COUNT(*) AS observation_count
            FROM traffic_observations
            WHERE hostname IS NOT NULL
              AND TRIM(hostname) <> ''
            GROUP BY LOWER(TRIM(hostname))
            ORDER BY observation_count DESC, hostname ASC
            LIMIT {$limit}
        ";

        $stmt = $this->db->query($sql);

        $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

        $result = [];

        foreach ($rows as $row) {
            $hostname = $this->normalizeHostname(
                (string)($row['hostname'] ?? '')
            );

            if ($hostname === null) {
                continue;
            }

            $result[] = [
                'hostname' => $hostname,
                'observation_count' => (int)($row['observation_count'] ?? 0),
            ];
        }

        return $result;
    }

    /**
     * Ambil evidence runtime untuk satu hostname.
     */
    private function collectEvidence(string $hostname): array
    {
        $stmt = $this->db->prepare("
            SELECT
                COUNT(*) AS observation_count,

                COUNT(DISTINCT router_id) AS router_count,

                COUNT(DISTINCT organization_id) AS organization_count,

                COUNT(DISTINCT customer_ip) AS customer_count,

                COUNT(DISTINCT destination_ip) AS destination_count,

                GROUP_CONCAT(
                    DISTINCT destination_port
                    ORDER BY destination_port
                    SEPARATOR ','
                ) AS ports,

                GROUP_CONCAT(
                    DISTINCT UPPER(protocol)
                    ORDER BY UPPER(protocol)
                    SEPARATOR ','
                ) AS protocols,

                GROUP_CONCAT(
                    DISTINCT connection_mark
                    ORDER BY connection_mark
                    SEPARATOR ','
                ) AS connection_marks,

                GROUP_CONCAT(
                    DISTINCT packet_mark
                    ORDER BY packet_mark
                    SEPARATOR ','
                ) AS packet_marks,

                GROUP_CONCAT(
                    DISTINCT hostname_source
                    ORDER BY hostname_source
                    SEPARATOR ','
                ) AS hostname_sources,

                MIN(first_seen_at) AS first_seen_at,

                MAX(last_seen_at) AS last_seen_at,

                COALESCE(SUM(orig_bytes), 0) AS orig_bytes,

                COALESCE(SUM(repl_bytes), 0) AS repl_bytes,

                COALESCE(SUM(orig_packets), 0) AS orig_packets,

                COALESCE(SUM(repl_packets), 0) AS repl_packets

            FROM traffic_observations
            WHERE LOWER(TRIM(hostname)) = ?
        ");

        $stmt->execute([$hostname]);

        $row = $stmt->fetch(PDO::FETCH_ASSOC);

        if (!$row) {
            return [
                'observation_count' => 0,
                'router_count' => 0,
                'organization_count' => 0,
                'customer_count' => 0,
                'destination_count' => 0,
                'ports' => [],
                'protocols' => [],
                'connection_marks' => [],
                'packet_marks' => [],
                'hostname_sources' => [],
                'first_seen_at' => null,
                'last_seen_at' => null,
                'orig_bytes' => 0,
                'repl_bytes' => 0,
                'orig_packets' => 0,
                'repl_packets' => 0,
            ];
        }

        return [
            'observation_count' => (int)($row['observation_count'] ?? 0),
            'router_count' => (int)($row['router_count'] ?? 0),
            'organization_count' => (int)($row['organization_count'] ?? 0),
            'customer_count' => (int)($row['customer_count'] ?? 0),
            'destination_count' => (int)($row['destination_count'] ?? 0),

            'ports' => $this->csvToArray($row['ports'] ?? ''),
            'protocols' => $this->csvToArray($row['protocols'] ?? ''),
            'connection_marks' => $this->csvToArray(
                $row['connection_marks'] ?? ''
            ),
            'packet_marks' => $this->csvToArray(
                $row['packet_marks'] ?? ''
            ),
            'hostname_sources' => $this->csvToArray(
                $row['hostname_sources'] ?? ''
            ),

            'first_seen_at' => $row['first_seen_at'] ?? null,
            'last_seen_at' => $row['last_seen_at'] ?? null,

            'orig_bytes' => (int)($row['orig_bytes'] ?? 0),
            'repl_bytes' => (int)($row['repl_bytes'] ?? 0),
            'orig_packets' => (int)($row['orig_packets'] ?? 0),
            'repl_packets' => (int)($row['repl_packets'] ?? 0),
        ];
    }

    /**
     * Central intelligence classifier.
     *
     * Urutan:
     * 1. exact/high-confidence services
     * 2. application signatures
     * 3. CDN/edge
     * 4. infrastructure
     * 5. unknown application
     */
    private function classifyHostname(
        string $hostname,
        array $evidence
    ): array {
        $host = strtolower($hostname);

        $result = [
            'provider' => null,
            'application' => null,
            'service' => null,
            'technical_classification' => 'APPLICATION',
            'business_category' => 'browser',
            'confidence' => 40,
            'normalized_domain' => $host,
        ];

        /*
         * ==========================================================
         * DNS
         * ==========================================================
         */

        $dnsRules = [
            'dns.google' => [
                'provider' => 'Google',
                'application' => 'Google DNS',
                'service' => 'Public DNS',
                'category' => 'infrastructure',
                'confidence' => 99,
            ],
            'one.one.one.one' => [
                'provider' => 'Cloudflare',
                'application' => 'Cloudflare DNS',
                'service' => 'Public DNS',
                'category' => 'infrastructure',
                'confidence' => 99,
            ],
            'dns.adguard.com' => [
                'provider' => 'AdGuard',
                'application' => 'AdGuard DNS',
                'service' => 'Public DNS',
                'category' => 'infrastructure',
                'confidence' => 99,
            ],
        ];

        foreach ($dnsRules as $domain => $rule) {
            if ($this->domainMatches($host, $domain)) {
                return $this->buildResult(
                    $result,
                    $rule['provider'],
                    $rule['application'],
                    $rule['service'],
                    'DNS',
                    $rule['category'],
                    $rule['confidence'],
                    $domain
                );
            }
        }

        /*
         * ==========================================================
         * YOUTUBE
         * ==========================================================
         */

        $youtubeDomains = [
            'youtube.com',
            'youtubei.googleapis.com',
            'googlevideo.com',
            'ytimg.com',
            'ggpht.com',
        ];

        foreach ($youtubeDomains as $domain) {
            if ($this->domainMatches($host, $domain)) {
                return $this->buildResult(
                    $result,
                    'Google',
                    'YouTube',
                    $this->youtubeService($host),
                    'APPLICATION',
                    'streaming',
                    99,
                    $this->knownDomainBase($host, $domain)
                );
            }
        }

        /*
         * ==========================================================
         * NETFLIX
         * ==========================================================
         */

        $netflixDomains = [
            'netflix.com',
            'nflxvideo.net',
            'nflximg.net',
            'nflxso.net',
            'nflxext.com',
        ];

        foreach ($netflixDomains as $domain) {
            if ($this->domainMatches($host, $domain)) {
                return $this->buildResult(
                    $result,
                    'Netflix',
                    'Netflix',
                    'Video Streaming',
                    'APPLICATION',
                    'streaming',
                    99,
                    $this->knownDomainBase($host, $domain)
                );
            }
        }

        $applicationGroups = [
            'game' => [
                'steamcommunity.com' => ['Steam', 'Game Platform'],
                'steampowered.com' => ['Steam', 'Game Platform'],
                'steamgames.com' => ['Steam', 'Game Platform'],
                'epicgames.com' => ['Epic Games', 'Game Platform'],
                'riotgames.com' => ['Riot Games', 'Game Platform'],
                'garena.com' => ['Garena', 'Game Platform'],
                'mobilelegends.com' => ['Mobile Legends', 'Online Game'],
                'pubg.com' => ['PUBG', 'Online Game'],
                'freefiremobile.com' => ['Free Fire', 'Online Game'],
                'playstation.com' => ['PlayStation', 'Game Platform'],
                'xboxlive.com' => ['Xbox', 'Game Platform'],
            ],
            'banking' => [
                'bca.co.id' => ['BCA', 'Internet Banking'],
                'bankmandiri.co.id' => ['Bank Mandiri', 'Internet Banking'],
                'bri.co.id' => ['BRI', 'Internet Banking'],
                'bni.co.id' => ['BNI', 'Internet Banking'],
                'cimbniaga.co.id' => ['CIMB Niaga', 'Internet Banking'],
                'danamon.co.id' => ['Danamon', 'Internet Banking'],
                'permatabank.com' => ['PermataBank', 'Internet Banking'],
            ],
            'e-wallet' => [
                'gopay.co.id' => ['GoPay', 'E-Wallet'],
                'ovo.id' => ['OVO', 'E-Wallet'],
                'dana.id' => ['DANA', 'E-Wallet'],
                'shopeepay.co.id' => ['ShopeePay', 'E-Wallet'],
                'linkaja.id' => ['LinkAja', 'E-Wallet'],
            ],
        ];

        foreach ($applicationGroups as $category => $domains) {
            foreach ($domains as $domain => [$provider, $service]) {
                if ($this->domainMatches($host, $domain)) {
                    return $this->buildResult(
                        $result,
                        $provider,
                        $provider,
                        $service,
                        'APPLICATION',
                        $category,
                        98,
                        $this->knownDomainBase($host, $domain)
                    );
                }
            }
        }

        /*
         * ==========================================================
         * META / FACEBOOK
         * ==========================================================
         */

        /*
         * ==========================================================
         * INSTAGRAM
         *
         * Harus diperiksa sebelum fbcdn.net karena hostname
         * Instagram juga dapat menggunakan jaringan Meta CDN.
         * ==========================================================
         */

        $instagramDomains = [
            'instagram.com',
            'cdninstagram.com',
        ];

        foreach ($instagramDomains as $domain) {
            if ($this->domainMatches($host, $domain)) {
                return $this->buildResult(
                    $result,
                    'Meta',
                    'Instagram',
                    'Social Media',
                    'APPLICATION',
                    'social',
                    99,
                    $this->knownDomainBase($host, $domain)
                );
            }
        }

        /*
         * Instagram melalui Meta CDN.
         */
        if (
            preg_match('/(^|\\.)instagram([.-]|$)/i', $host)
            && $this->domainChainMatches($host, 'fbcdn.net')
        ) {
            return $this->buildResult(
                $result,
                'Meta',
                'Instagram',
                'Social Media / Meta CDN',
                'APPLICATION',
                'social',
                98,
                'fbcdn.net'
            );
        }

        /*
         * ==========================================================
         * META / FACEBOOK
         * ==========================================================
         */

        $facebookDomains = [
            'facebook.com',
            'facebook.net',
            'fbcdn.net',
        ];

        foreach ($facebookDomains as $domain) {
            if ($this->domainMatches($host, $domain)) {
                return $this->buildResult(
                    $result,
                    'Meta',
                    'Facebook',
                    'Social Network',
                    'APPLICATION',
                    'social',
                    99,
                    $this->knownDomainBase($host, $domain)
                );
            }
        }

        /*
         * ==========================================================
         * MESSENGER
         * ==========================================================
         */

        if ($this->domainMatches($host, 'messenger.com')) {
            return $this->buildResult(
                $result,
                'Meta',
                'Messenger',
                'Instant Messaging',
                'APPLICATION',
                'chat',
                99,
                'messenger.com'
            );
        }
        /*
         * ==========================================================
         * WHATSAPP
         * ==========================================================
         */

        $whatsappDomains = [
            'whatsapp.com',
            'whatsapp.net',
        ];

        foreach ($whatsappDomains as $domain) {
            if ($this->domainMatches($host, $domain)) {
                return $this->buildResult(
                    $result,
                    'Meta',
                    'WhatsApp',
                    'Messaging',
                    'APPLICATION',
                    'chat',
                    99,
                    $this->knownDomainBase($host, $domain)
                );
            }
        }

        /*
         * ==========================================================
         * TIKTOK / BYTEDANCE
         * ==========================================================
         */

        $tiktokDomains = [
            'tiktok.com',
            'tiktokcdn.com',
            'tiktokv.com',
            'tiktokcdn-eu.com',
            'byteoversea.com',
            'byteoversea.net',
            'ibytedtos.com',
            'ibyteimg.com',
        ];

        foreach ($tiktokDomains as $domain) {
            if (
                $this->domainMatches($host, $domain)
                || $this->domainChainMatches($host, $domain)
            ) {
                $technical = 'APPLICATION';

                if (
                    $this->domainMatches($host, 'edgesuite.net')
                    || $this->domainMatches($host, 'edgekey.net')
                    || $this->domainMatches($host, 'akadns.net')
                    || $this->domainMatches($host, 'fastly.net')
                ) {
                    $technical = 'CDN';
                }

                return $this->buildResult(
                    $result,
                    'ByteDance',
                    'TikTok',
                    'Short Video / Social Media',
                    $technical,
                    'social',
                    97,
                    $this->knownDomainBase($host, $domain)
                );
            }
        }

        /*
         * ==========================================================
         * SHOPEE
         * ==========================================================
         */

        $shopeeDomains = [
            'shopee.co.id',
            'shopee.com',
            'shopee.sg',
            'shopee.co.th',
            'shopee.com.my',
            'shopee.vn',
            'shopee.ph',
            'shopee.tw',
        ];

        foreach ($shopeeDomains as $domain) {
            if ($this->domainMatches($host, $domain)) {
                return $this->buildResult(
                    $result,
                    'Sea Limited',
                    'Shopee',
                    'E-Commerce',
                    'APPLICATION',
                    'e-commerce',
                    99,
                    $this->knownDomainBase($host, $domain)
                );
            }
        }

        /*
         * ==========================================================
         * KWAI / KUAISHOU
         * ==========================================================
         */

        $kwaiDomains = [
            'kwai.com',
            'kwai.net',
            'kwai-pro.com',
            'kwaipros.com',
        ];

        foreach ($kwaiDomains as $domain) {
            if (
                $this->domainMatches($host, $domain)
                || $this->domainChainMatches($host, $domain)
            ) {
                $technical = 'APPLICATION';

                if (
                    $this->domainMatches($host, 'akadns.net')
                    || $this->domainMatches($host, 'akamaized.net')
                    || $this->domainMatches($host, 'edgekey.net')
                    || $this->domainMatches($host, 'edgesuite.net')
                ) {
                    $technical = 'CDN';
                }

                return $this->buildResult(
                    $result,
                    'Kuaishou',
                    'Kwai',
                    'Short Video / Social Media',
                    $technical,
                    'social',
                    96,
                    $this->knownDomainBase($host, $domain)
                );
            }
        }

        /*
         * ==========================================================
         * CAPCUT
         * ==========================================================
         */

        $capcutDomains = [
            'capcut.com',
            'capcutapi.com',
        ];

        foreach ($capcutDomains as $domain) {
            if (
                $this->domainMatches($host, $domain)
                || $this->domainChainMatches($host, $domain)
            ) {
                $technical = 'APPLICATION';

                if (
                    $this->domainMatches($host, 'edgesuite.net')
                    || $this->domainMatches($host, 'edgekey.net')
                    || $this->domainMatches($host, 'akamaized.net')
                ) {
                    $technical = 'CDN';
                }

                return $this->buildResult(
                    $result,
                    'ByteDance',
                    'CapCut',
                    'Video Editing',
                    $technical,
                    'content-creation',
                    96,
                    $this->knownDomainBase($host, $domain)
                );
            }
        }

        /*
         * ==========================================================
         * SECURITY
         * ==========================================================
         */

        $securityRules = [
            'letsencrypt.org' => [
                "Let's Encrypt",
                'Certificate / PKI',
                'Certificate Authority',
            ],
            'lencr.org' => [
                "Let's Encrypt",
                'Certificate / PKI',
                'Certificate Authority',
            ],
            'mcafee.com' => [
                'McAfee',
                'McAfee Security',
                'Security Software',
            ],
        ];

        foreach ($securityRules as $domain => $rule) {
            if ($this->domainMatches($host, $domain)) {
                return $this->buildResult(
                    $result,
                    $rule[0],
                    $rule[1],
                    $rule[2],
                    'SECURITY',
                    'security',
                    97,
                    $this->knownDomainBase($host, $domain)
                );
            }
        }

        /*
         * ==========================================================
         * GOOGLE ECOSYSTEM
         * ==========================================================
         *
         * IMPORTANT:
         * Google APIs are NOT automatically Streaming.
         */

        $googleServiceRules = [
            'googleapis.com' => [
                'Google',
                'Google APIs',
                'Cloud / API Services',
            ],
            'gstatic.com' => [
                'Google',
                'Google Static Services',
                'Web / Application Infrastructure',
            ],
            'google.com' => [
                'Google',
                'Google Services',
                'Web / Cloud Services',
            ],
            'android.com' => [
                'Google',
                'Android',
                'Mobile Platform',
            ],
            'android.clients.google.com' => [
                'Google',
                'Google Play / Android Services',
                'Mobile Platform',
            ],
        ];

        foreach ($googleServiceRules as $domain => $rule) {
            if ($this->domainMatches($host, $domain)) {
                return $this->buildResult(
                    $result,
                    $rule[0],
                    $rule[1],
                    $rule[2],
                    'CLOUD',
                    'infrastructure',
                    94,
                    $this->knownDomainBase($host, $domain)
                );
            }
        }

        /*
         * ==========================================================
         * AD / ANALYTICS
         * ==========================================================
         */

        $analyticsRules = [
            'appsflyersdk.com' => [
                'AppsFlyer',
                'AppsFlyer SDK',
                'Mobile Attribution / Analytics',
            ],
            'app-measurement.com' => [
                'Google',
                'Firebase Analytics',
                'Mobile Analytics',
            ],
            'applovin.com' => [
                'AppLovin',
                'AppLovin',
                'Mobile Advertising',
            ],
            'doubleclick.net' => [
                'Google',
                'Google Ads',
                'Advertising',
            ],
            'pangle.io' => [
                'ByteDance',
                'Pangle',
                'Advertising',
            ],
        ];

        foreach ($analyticsRules as $domain => $rule) {
            if (
                $this->domainMatches($host, $domain)
                || $this->domainChainMatches($host, $domain)
            ) {
                return $this->buildResult(
                    $result,
                    $rule[0],
                    $rule[1],
                    $rule[2],
                    'ANALYTICS_ADVERTISING',
                    'advertising',
                    94,
                    $this->knownDomainBase($host, $domain)
                );
            }
        }

        /*
         * ==========================================================
         * DEVICE / VENDOR ECOSYSTEM
         * ==========================================================
         */

        $vendorRules = [
            'apple.com' => [
                'Apple',
                'Apple Services',
                'Device / Platform Services',
            ],
            'apple-dns.net' => [
                'Apple',
                'Apple DNS',
                'DNS / Device Services',
            ],
            'xiaomi.com' => [
                'Xiaomi',
                'Xiaomi Services',
                'Device / Platform Services',
            ],
            'vivo.com.cn' => [
                'Vivo',
                'Vivo Services',
                'Device / Platform Services',
            ],
            'heytapdl.com' => [
                'HeyTap / OPPO',
                'HeyTap Services',
                'Device / Platform Services',
            ],
        ];

        foreach ($vendorRules as $domain => $rule) {
            if (
                $this->domainMatches($host, $domain)
                || $this->domainChainMatches($host, $domain)
            ) {
                $technical = 'DEVICE_PLATFORM';

                if ($domain === 'apple-dns.net') {
                    $technical = 'DNS';
                }

                return $this->buildResult(
                    $result,
                    $rule[0],
                    $rule[1],
                    $rule[2],
                    $technical,
                    'infrastructure',
                    92,
                    $this->knownDomainBase($host, $domain)
                );
            }
        }

        /*
         * ==========================================================
         * AMAZON / AWS INFRASTRUCTURE
         * ==========================================================
         */

        if (
            $this->domainMatches($host, 'amazonaws.com')
            || $this->domainChainMatches($host, 'amazonaws.com')
        ) {
            return $this->buildResult(
                $result,
                'Amazon Web Services',
                'AWS Infrastructure',
                'Cloud / Infrastructure',
                'CLOUD',
                'infrastructure',
                94,
                'amazonaws.com'
            );
        }
        /*
         * ==========================================================
         * BYTEDANCE MAP / FASTLY
         * ==========================================================
         *
         * Fastly adalah delivery layer.
         * Hostname api.bytedance.map.fastly.net memberikan
         * bukti aplikasi/provider yang lebih spesifik.
         * Jangan biarkan jatuh ke generic Fastly.
         */

        if ($this->domainMatches($host, 'bytedance.map.fastly.net')) {
            return $this->buildResult(
                $result,
                'ByteDance',
                'ByteDance Map',
                'Maps & Location',
                'CDN',
                'infrastructure',
                94,
                'bytedance.map.fastly.net'
            );
        }

        /*
         * ==========================================================
         * CDN / EDGE
         * ==========================================================
         */

        $cdnRules = [
            'akamaiedge.net' => 'Akamai',
            'akamai.net' => 'Akamai',
            'akamaized.net' => 'Akamai',
            'edgekey.net' => 'Akamai',
            'edgesuite.net' => 'Akamai',
            'cloudflare.net' => 'Cloudflare',
            'cloudflare.com' => 'Cloudflare',
            'fastly.net' => 'Fastly',
            'fastlylb.net' => 'Fastly',
            'cloudfront.net' => 'Amazon CloudFront',
        ];

        foreach ($cdnRules as $domain => $provider) {
            if ($this->domainMatches($host, $domain)) {
                return $this->buildResult(
                    $result,
                    $provider,
                    null,
                    'CDN / Edge Infrastructure',
                    'CDN',
                    'infrastructure',
                    91,
                    $this->knownDomainBase($host, $domain)
                );
            }
        }

        /*
         * ==========================================================
         * GENERIC INFRASTRUCTURE
         * ==========================================================
         */

        $infrastructureTokens = [
            'api.',
            'cdn.',
            'static.',
            'assets.',
            'telemetry.',
            'metrics.',
            'crl.',
            'ocsp.',
            'download.',
            'update.',
            'push.',
        ];

        foreach ($infrastructureTokens as $token) {
            if (
                $this->containsToken($host, $token)
            ) {
                return $this->buildResult(
                    $result,
                    null,
                    null,
                    'Service Infrastructure',
                    'INFRASTRUCTURE',
                    'infrastructure',
                    70,
                    $this->parentDomain($host)
                );
            }
        }

        /*
         * ==========================================================
         * UNKNOWN
         * ==========================================================
         */

        $confidence = 40;

        $observationCount = (int)(
            $evidence['observation_count'] ?? 0
        );

        if ($observationCount >= 5) {
            $confidence += 5;
        }

        if ($observationCount >= 20) {
            $confidence += 5;
        }

        if ((int)($evidence['customer_count'] ?? 0) >= 2) {
            $confidence += 3;
        }

        if ((int)($evidence['router_count'] ?? 0) >= 2) {
            $confidence += 3;
        }

        $confidence = min(65, $confidence);

        return $this->buildResult(
            $result,
            null,
            null,
            null,
            'APPLICATION',
            'browser',
            $confidence,
            $this->parentDomain($host)
        );
    }

    /**
     * Build a normalized intelligence result.
     */
    private function buildResult(
        array $base,
        ?string $provider,
        ?string $application,
        ?string $service,
        string $technical,
        string $category,
        float $confidence,
        string $normalizedDomain
    ): array {
        $base['provider'] = $provider;
        $base['application'] = $application;
        $base['service'] = $service;
        $base['technical_classification'] = $technical;
        $base['business_category'] = $category;
        $base['confidence'] = min(100, max(0, $confidence));
        $base['normalized_domain'] = $normalizedDomain;

        return $base;
    }

    /**
     * Domain boundary matching.
     *
     * IMPORTANT:
     * xnxx.com MUST NOT match x.com.
     */
    private function domainMatches(
        string $hostname,
        string $domain
    ): bool {
        $hostname = strtolower(rtrim(trim($hostname), '.'));
        $domain = strtolower(rtrim(trim($domain), '.'));

        if ($hostname === '' || $domain === '') {
            return false;
        }

        return $hostname === $domain ||
            $this->endsWith($hostname, '.' . $domain);
    }

    private function containsToken(
        string $hostname,
        string $token
    ): bool {
        if ($token === '') {
            return false;
        }

        return strpos($hostname, $token) !== false;
    }

    /**
     * Domain-chain matching.
     *
     * Contoh:
     *   foo.tiktokv.com.bytewlb.akadns.net
     *   api.pangle.io.ttdns2.com
     *   foo.kwai-pro.com.akadns.net
     *
     * Berbeda dengan strpos(), pencocokan dilakukan pada
     * boundary domain sehingga tidak mudah menghasilkan
     * false-positive.
     */
    private function domainChainMatches(
        string $hostname,
        string $domain
    ): bool {
        $hostname = strtolower(rtrim(trim($hostname), '.'));
        $domain = strtolower(rtrim(trim($domain), '.'));

        if ($hostname === '' || $domain === '') {
            return false;
        }

        if ($this->domainMatches($hostname, $domain)) {
            return true;
        }

        return strpos($hostname, '.' . $domain . '.') !== false
            || strpos($hostname, '.' . $domain) !== false;
    }

    private function endsWith(
        string $haystack,
        string $needle
    ): bool {
        if ($needle === '') {
            return true;
        }

        return substr(
            $haystack,
            -strlen($needle)
        ) === $needle;
    }

    private function normalizeHostname(
        string $hostname
    ): ?string {
        $hostname = strtolower(trim($hostname));
        $hostname = rtrim($hostname, '.');

        if ($hostname === '') {
            return null;
        }

        if (strlen($hostname) > 253) {
            return null;
        }

        if (strpos($hostname, '.') === false) {
            return null;
        }

        if (filter_var($hostname, FILTER_VALIDATE_IP)) {
            return null;
        }

        if (strpos($hostname, '..') !== false) {
            return null;
        }

        if (
            !preg_match(
                '/^[a-z0-9][a-z0-9._-]*[a-z0-9]$/i',
                $hostname
            )
        ) {
            return null;
        }

        return $hostname;
    }

    private function csvToArray(string $value): array
    {
        if (trim($value) === '') {
            return [];
        }

        $parts = explode(',', $value);
        $result = [];

        foreach ($parts as $part) {
            $part = trim($part);

            if ($part !== '') {
                $result[] = $part;
            }
        }

        return array_values(array_unique($result));
    }

    private function knownDomainBase(
        string $hostname,
        string $domain
    ): string {
        /*
         * Direct domain:
         *   youtube.com
         *   shopee.co.id
         *   amazonaws.com
         *
         * Domain-chain:
         *   tiktokv.com.bytewlb.akadns.net
         *   kwai-pro.com.akadns.net
         *   pangle.io.ttdns2.com
         *
         * Jika domain aplikasi ditemukan di dalam chain,
         * gunakan domain tersebut sebagai normalized_domain,
         * bukan domain CDN/provider paling belakang.
         */
        if (
            $this->domainMatches($hostname, $domain)
            || $this->domainChainMatches($hostname, $domain)
        ) {
            return strtolower($domain);
        }

        return $this->parentDomain($hostname);
    }

    private function parentDomain(string $hostname): string
    {
        $parts = explode('.', strtolower($hostname));

        $count = count($parts);

        if ($count <= 2) {
            return $hostname;
        }

        return $parts[$count - 2] . '.' . $parts[$count - 1];
    }

    private function youtubeService(string $hostname): string
    {
        if (
            $this->domainMatches(
                $hostname,
                'googlevideo.com'
            )
        ) {
            return 'YouTube Video Delivery';
        }

        if (
            $this->domainMatches(
                $hostname,
                'ytimg.com'
            )
        ) {
            return 'YouTube Static Media';
        }

        if (
            $this->domainMatches(
                $hostname,
                'ggpht.com'
            )
        ) {
            return 'YouTube Image / Media';
        }

        return 'YouTube';
    }
}
