<?php
declare(strict_types=1);
require_once __DIR__ . '/../app/bootstrap.php';
use BAJAMA\Core\Auth; use BAJAMA\Core\License; use BAJAMA\Core\RBAC; use BAJAMA\Core\Tenant;
Auth::requireLogin();$db=db();License::requireFeature($db,'mikrotik');RBAC::require($db,'network.view');$organizationId=Tenant::id();
$s=$db->prepare('SELECT r.id,r.name,r.host,r.status,r.last_tested_at,r.last_error,r.updated_at,(SELECT COUNT(*) FROM network_load_balances lb WHERE lb.router_id=r.id AND lb.organization_id=r.organization_id AND lb.enabled=1) load_balance_count,(SELECT COUNT(*) FROM network_firewall_rules fw WHERE fw.router_id=r.id AND fw.organization_id=r.organization_id AND fw.enabled=1) firewall_count FROM mikrotik_routers r WHERE r.organization_id=? ORDER BY r.name');$s->execute([$organizationId]);$routers=$s->fetchAll(PDO::FETCH_ASSOC);
$s=$db->prepare('SELECT COUNT(*) FROM network_static_ips WHERE organization_id=? AND enabled=1');$s->execute([$organizationId]);$staticCount=(int)$s->fetchColumn();$s=$db->prepare('SELECT COUNT(*) FROM network_hotspot_vouchers WHERE organization_id=? AND status="READY" AND enabled=1');$s->execute([$organizationId]);$voucherCount=(int)$s->fetchColumn();$s=$db->prepare('SELECT COUNT(*) FROM network_ftth_services WHERE organization_id=? AND status="ONLINE" AND enabled=1');$s->execute([$organizationId]);$ftthOnline=(int)$s->fetchColumn();function mon_h($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}$pageTitle='Network Monitoring';$networkLayout=true;$networkActive='monitoring';ob_start();
?>
<div class="container-fluid py-4"><div class="mb-4"><h1>Network Monitoring</h1><p class="text-muted mb-0">Ringkasan kesehatan router, firewall, load balance dan layanan pelanggan tenant aktif.</p></div><div class="row g-3 mb-4"><div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted">Router</div><div class="display-6"><?=count($routers)?></div></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted">Static IP Aktif</div><div class="display-6"><?=$staticCount?></div></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted">Voucher Ready</div><div class="display-6"><?=$voucherCount?></div></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted">FTTH Online</div><div class="display-6"><?=$ftthOnline?></div></div></div></div></div><div class="card"><div class="card-header">Status Router dan Modul</div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Router</th><th>Host</th><th>Status</th><th>Last Tested</th><th>Load Balance</th><th>Firewall Rules</th><th>Last Error</th></tr></thead><tbody><?php foreach($routers as $r):?><tr><td><?=mon_h($r['name'])?></td><td><code><?=mon_h($r['host'])?></code></td><td><span class="badge <?=in_array($r['status'],['ONLINE'],true)?'text-bg-success':($r['status']==='ERROR'?'text-bg-danger':'text-bg-secondary')?>"><?=mon_h($r['status'])?></span></td><td><?=mon_h($r['last_tested_at']??'-')?></td><td><?=$r['load_balance_count']?></td><td><?=$r['firewall_count']?></td><td><?=mon_h($r['last_error']??'-')?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<?php $content=ob_get_clean();$networkLayout=false;require __DIR__.'/../app/layout/layout.php';
